export default function About() {
    return (
        <section className="py-20 bg-gray-50">
              <div className="container mx-auto px-4">
                      <div className="text-center mb-16">
                                <h2 className="text-3xl md:text-4xl font-bold text-gray-800 mb-4">
                                            Tentang Desa Cemara Wetan
                                                      </h2>
                                                                <p className="text-xl text-gray-600 max-w-2xl mx-auto">
                                                                            Desa Cemara Wetan merupakan salah satu desa di Kecamatan Cantigi, Kabupaten Indramayu 
                                                                                        yang terkenal dengan potensi perikanan tambak dan pertaniannya.
                                                                                                  </p>
                                                                                                          </div>
                                                                                                                  
                                                                                                                          <div className="grid md:grid-cols-3 gap-8">
                                                                                                                                    <div className="text-center p-8 bg-white rounded-2xl shadow-lg hover:shadow-2xl transition-all">
                                                                                                                                                <div className="w-20 h-20 bg-primary rounded-full mx-auto mb-6 flex items-center justify-center">
                                                                                                                                                              <svg className="w-10 h-10 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                                                                                                                                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                                                                                                                                                                                            </svg>
                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                    <h3 className="text-2xl font-bold mb-4">3.847</h3>
                                                                                                                                                                                                                                <p className="text-gray-600 font-semibold">Jiwa (2023)</p>
                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                              <div className="text-center p-8 bg-white rounded-2xl shadow-lg hover:shadow-2xl transition-all">
                                                                                                                                                                                                                                                                          <div className="w-20 h-20 bg-secondary rounded-full mx-auto mb-6 flex items-center justify-center">
                                                                                                                                                                                                                                                                                        <svg className="w-10 h-10 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                                                                                                                                                                                                                                                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                                                                                                                                                                                                                                                                                                      </svg>
                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                              <h3 className="text-2xl font-bold mb-4">412 Ha</h3>
                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-600 font-semibold">Luas Wilayah</p>
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-center p-8 bg-white rounded-2xl shadow-lg hover:shadow-2xl transition-all">
                                                                                                                                                                                                                                                                                                                                                                                                    <div className="w-20 h-20 bg-accent rounded-full mx-auto mb-6 flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                  <svg className="w-10 h-10 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                                                                                                                                                                                                                                                                                                                                                                                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="text-2xl font-bold mb-4">12</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-gray-600 font-semibold">RT/RW</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
}