export default function Contact() {
    return (
        <section className="py-20 bg-gradient-to-r from-primary to-secondary text-white">
              <div className="container mx-auto px-4">
                      <div className="grid md:grid-cols-2 gap-12 items-center">
                                <div>
                                            <h2 className="text-3xl md:text-4xl font-bold mb-6">
                                                          Kantor Desa Cemara Wetan
                                                                      </h2>
                                                                                  <p className="text-xl mb-8 opacity-90">
                                                                                                Layanan Administrasi Kependudukan
                                                                                                              <br />Senin - Sabtu: 08.00 - 16.00 WIB
                                                                                                                          </p>
                                                                                                                                      <div className="space-y-4">
                                                                                                                                                    <div className="flex items-center">
                                                                                                                                                                    <div className="w-12 h-12 bg-accent rounded-full flex items-center justify-center mr-4 text-lg">
                                                                                                                                                                                      📞
                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                        <p className="font-semibold">Kepala Desa</p>
                                                                                                                                                                                                                                                          <p>0236-xxx-xxx</p>
                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                      <div className="flex items-center">
                                                                                                                                                                                                                                                                                                                      <div className="w-12 h-12 bg-accent rounded-full flex items-center justify-center mr-4">
                                                                                                                                                                                                                                                                                                                                        📱
                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                          <p className="font-semibold">WhatsApp</p>
                                                                                                                                                                                                                                                                                                                                                                                                            <p>0812-3456-7890</p>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="w-12 h-12 bg-accent rounded-full flex items-center justify-center mr-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          📍
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="font-semibold">Alamat</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>Ds. Cemara Wetan, Kec. Cantigi<br/>Kab. Indramayu 45262</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Form sama */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
}