export default function News() {
    const news = [
        {
              title: "Prabowo Inaugurasi Revitalisasi Tambak Pantura Indramayu",
                    date: "20 Des 2024",
                          excerpt: "Presiden Prabowo Subianto resmikan program revitalisasi 5.000 Ha tambak pantura Indramayu dengan investasi Rp 2,5 Triliun. Desa Cemara Wetan termasuk penerima manfaat utama.",
                                image: "/images/news-tambak.jpg",
                                      category: "PENTING"
                                          },
                                              {
                                                    title: "Gubernur Jabar: Target Swasembada Ikan 2025 Tercapai",
                                                          date: "18 Des 2024",
                                                                excerpt: "Dedi Mulyadi umumkan Indramayu jadi lumbung ikan nasional berkat tambak modernisasi. Produksi udang vaname naik 300%.",
                                                                      image: "/images/news-jabar.jpg",
                                                                            category: "JABAR"
                                                                                },
                                                                                    {
                                                                                          title: "Presiden Prabowo Kunjungi Indramayu, Fokus Ekonomi Pantura",
                                                                                                date: "15 Des 2024",
                                                                                                      excerpt: "Presiden RI ke-8 instruksikan percepatan infrastruktur Pantura Jabar termasuk Jembatan Cantigi dan pelabuhan perikanan.",
                                                                                                            image: "/images/news-presiden.jpg",
                                                                                                                  category: "NASIONAL"
                                                                                                                      },
                                                                                                                          {
                                                                                                                                title: "Musrenbang Desa Cemara Wetan 2025 Prioritaskan Tambak",
                                                                                                                                      date: "12 Des 2024",
                                                                                                                                            excerpt: "Kepala Desa Cemara Wetan usulkan anggaran Rp 500 juta untuk modernisasi 50 Ha tambak udang windu tahun 2025.",
                                                                                                                                                  image: "/images/news-desa.jpg",
                                                                                                                                                        category: "DESA"
                                                                                                                                                            },
                                                                                                                                                                {
                                                                                                                                                                      title: "Dedi Mulyadi Bagi BLT Tambak Rp 2 Juta per Petambak",
                                                                                                                                                                            date: "10 Des 2024",
                                                                                                                                                                                  excerpt: "Gubernur Jabar salurkan bantuan langsung tunai kepada 2.500 petambak di Indramayu termasuk warga Cemara Wetan.",
                                                                                                                                                                                        image: "/images/news-blt.jpg",
                                                                                                                                                                                              category: "JABAR"
                                                                                                                                                                                                  },
                                                                                                                                                                                                      {
                                                                                                                                                                                                            title: "Revitalisasi Tambak Pantura Targetkan Ekspor 100.000 Ton",
                                                                                                                                                                                                                  date: "8 Des 2024",
                                                                                                                                                                                                                        excerpt: "Kementerian Kelautan targetkan ekspor udang dan bandeng dari Pantura Jabar tembus pasar China & Jepang 2025.",
                                                                                                                                                                                                                              image: "/images/news-ekspor.jpg",
                                                                                                                                                                                                                                    category: "PENTING"
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                          ];

                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                <section className="py-20 bg-gray-50">
                                                                                                                                                                                                                                                      <div className="container mx-auto px-4">
                                                                                                                                                                                                                                                              <div className="text-center mb-16">
                                                                                                                                                                                                                                                                        <h2 className="text-3xl md:text-4xl font-bold text-gray-800 mb-4">
                                                                                                                                                                                                                                                                                    Berita Terkini
                                                                                                                                                                                                                                                                                              </h2>
                                                                                                                                                                                                                                                                                                        <p className="text-xl text-gray-600">Update terkini Desa Cemara Wetan, Jawa Barat & Nasional</p>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                                                                                                                                                                                                                                                                                                                                          {news.map((item, index) => (
                                                                                                                                                                                                                                                                                                                                                      <div key={index} className="bg-white rounded-2xl overflow-hidden shadow-lg hover:shadow-2xl transition-all group">
                                                                                                                                                                                                                                                                                                                                                                    <div className="h-48 bg-gradient-to-r from-primary to-secondary flex items-center justify-center text-white text-2xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                    {item.category}
                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                <div className="p-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-xs bg-accent text-primary px-3 py-1 rounded-full w-fit mb-3 font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {item.date}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-xl font-bold mb-3 line-clamp-2 group-hover:text-primary transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {item.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-gray-600 mb-4 line-clamp-3">{item.excerpt}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="text-primary font-semibold hover:underline flex items-center gap-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Baca Selengkapnya <span>→</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
}